collections:
  - collection_name: assets
    indexes:
      - index_name: tags_index
        fields:
          - name: "tenant_id"
            order: 1
          - name: "is_active"
            order: 1
          - name: "tags.name"
            order: 1
          - name: "tags.value"
            order: 1
          - name: "created_at"
            order: -1
          - name: "_id"
            order: -1

