name: Docker Hello World

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          echo -e 'FROM alpine:latest\nCMD ["echo", "Hello World"]' > Dockerfile
          docker build -t hello-world-image .

      - name: Run Docker image
        run: |
          docker run hello-world-image
