name: PR Automation

on:
  pull_request:

jobs:
  pr-info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Print PR Info using env vars
        run: |
          echo "Organization Name: $GITHUB_REPOSITORY_OWNER"
          echo "Repository Name: ${GITHUB_REPOSITORY#*/}"
          echo "PR Number: ${PR_NUMBER}"
          echo "Commit SHA: ${GITHUB_SHA}"
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_SHA: ${{ github.event.pull_request.head.sha }}
