name: PR Automation

on:
  pull_request:

jobs:
  pr-info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Print PR Info using env vars
        run: |
          docker load -i vulnerable.tar
          
          sudo apt-get update && sudo apt-get install -y curl git
          curl -L https://jit-cli.s3.us-east-1.amazonaws.com/jit-cli/sc-20437-bug-squashing-improve-review/jit-cli-amd64-slim -o jit-cli
          chmod +x jit-cli
          
          ./jit-cli container --image $IMAGE --tracking-name $TRACKING_NAME --organization $GITHUB_REPOSITORY_OWNER --repo ${GITHUB_REPOSITORY#*/} --pull-request ${PR_NUMBER} --commit-id ${COMMIT_ID} --fail-on-findings
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }} 
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          COMMIT_ID: ${{ github.event.pull_request.head.sha }}  
          JIT_CLIENT_ID: ${{ secrets.JIT_CLIENT_ID }}
          JIT_SECRET_KEY: ${{ secrets.JIT_SECRET_KEY }}
          ENV_NAME: bandit
          IMAGE: local-gitleaks
          TRACKING_NAME: test/gitleaks
